site_name: python数据结构和算法 - 中文版
repo_name: python数据结构和算法 - 中文版
repo_url: https://github.com/hellowac/pythonds-zh-cn/
site_description: 通过python解决算法和数据结构问题

# 配置主题，在mkdocs.yml文件下
theme:
  name: material
  language: zh
  palette:
    primary: teal # 主题色
    accent: blue # 提示颜色
  features:
    - content.code.copy # 代码支持拷贝
    - content.tabs.link # 内容tabs支持
    - navigation.tabs # 顶部导航
    - navigation.tabs.sticky # 顶部导航粘连
    - navigation.indexes # 导航index页面支持
    # - navigation.sections # 全部展开(非折叠状态)
    # - navigation.expand # 子目录展开
    - navigation.top # 返回顶部按钮
    - toc.follow # 页面目录支持

# 插件
plugins:
  - glightbox
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized: # 支持文档创建时间显示， https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
      locale: zh
      enable_creation_date: true
      type: date

# markdown解析扩展
markdown_extensions:
  - tables
  - admonition
  - attr_list
  - footnotes # 引用支持            https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes
  - def_list # 键-值组合的list     https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes
  - toc: # 页面目录支持         https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
      permalink: true # 标题锚点支持
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # 区分大小写的显示标题
        kwds:
          case: lower # 全小写支持
  - md_in_html # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes
  # pymdownx 扩展，参考：https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.inlinehilite # 单行高亮, 参考: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines
  - pymdownx.critic # 支持部分字段格式化，参考：https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.highlight # 支持代码块高亮显示
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true # checkbox 支持
  - pymdownx.superfences: # 注释 :
      # preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # 支持内容tab, https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
      alternate_style: true
  - pymdownx.caret # 下划线, 上标 : https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=caret#caret-mark-tilde
    #               https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.mark # 标记 :https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=caret#caret-mark-tilde
    #      https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.tilde # 删除线, 下标  参考: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=caret#caret-mark-tilde
    #                   https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.arithmatex:
      generic: true

# 扩展支持， 支持数学符号
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  # - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs

# 页面导航
nav:
  - 首页: index.md
  - 1. 引言:
      - c1/index.md
      - c1/s1.md
      - c1/s2.md
      - c1/s3.md
      - c1/s4.md
      - c1/s5.md
      - c1/s6.md
      - c1/s7.md
      - c1/s8.md
      - c1/s9.md
      - c1/s10.md
      - c1/s11.md
      - c1/s12.md
      - c1/s13.md
      - c1/s14.md
      - c1/s15.md
      - c1/s16.md
  - 2. 算法分析:
      - c2/index.md
      - c2/s1.md
      - c2/s2.md
      - c2/s3.md
      - c2/s4.md
      - c2/s5.md
      - c2/s6.md
      - c2/s7.md
      - c2/s8.md
      - c2/s9.md
      - c2/s10.md
  - 3. 基本数据结构:
      - c3/index.md
      - c3/s1.md
      - c3/s2.md
      - c3/s3.md
      - c3/s4.md
      - c3/s5.md
      - c3/s6.md
      - c3/s7.md
      - c3/s8.md
      - c3/s9.md
      - c3/s10.md
      - c3/s11.md
      - c3/s12.md
      - c3/s13.md
      - c3/s14.md
      - c3/s15.md
      - c3/s16.md
      - c3/s17.md
      - c3/s18.md
      - c3/s19.md
      - c3/s20.md
      - c3/s21.md
      - c3/s22.md
      - c3/s23.md
      - c3/s24.md
      - c3/s25.md
      - c3/s26.md
  - 4. 递归:
      - c4/index.md
      - c4/s1.md
      - c4/s2.md
      - c4/s3.md
      - c4/s4.md
      - c4/s5.md
      - c4/s6.md
      - c4/s7.md
      - c4/s8.md
      - c4/s9.md
      - c4/s10.md
      - c4/s11.md
      - c4/s12.md
      - c4/s13.md
      - c4/s14.md
      - c4/s15.md
  - 5. 搜索与排序:
      - c5/index.md
      - c5/s1.md
      - c5/s2.md
      - c5/s3.md
      - c5/s4.md
      - c5/s5.md
      - c5/s6.md
      - c5/s7.md
      - c5/s8.md
      - c5/s9.md
      - c5/s10.md
      - c5/s11.md
      - c5/s12.md
      - c5/s13.md
      - c5/s14.md
      - c5/s15.md
  - 6. 树和树算法:
      - c6/index.md
      - c6/s1.md
      - c6/s2.md
      - c6/s3.md
      - c6/s4.md
      - c6/s5.md
      - c6/s6.md
      - c6/s7.md
      - c6/s8.md
      - c6/s9.md
      - c6/s10.md
      - c6/s11.md
      - c6/s12.md
      - c6/s13.md
      - c6/s14.md
      - c6/s15.md
      - c6/s16.md
      - c6/s17.md
      - c6/s18.md
      - c6/s19.md
      - c6/s20.md
      - c6/s21.md
      - c6/s22.md
  - 7. 图和图算法:
      - c7/index.md
      - c7/s1.md
      - c7/s2.md
      - c7/s3.md
      - c7/s4.md
      - c7/s5.md
      - c7/s6.md
      - c7/s7.md
      - c7/s8.md
      - c7/s9.md
      - c7/s10.md
      - c7/s11.md
      - c7/s12.md
      - c7/s13.md
      - c7/s14.md
      - c7/s15.md
      - c7/s16.md
      - c7/s17.md
      - c7/s18.md
      - c7/s19.md
      - c7/s20.md
      - c7/s21.md
      - c7/s22.md
      - c7/s23.md
      - c7/s24.md
      - c7/s25.md
  - 8. 高级主题:
      - c8/index.md
      - c8/s1.md
      - c8/s2.md
      - c8/s3.md
      - c8/s4.md
      - c8/s5.md
      - c8/s6.md
