site_name: python数据结构和算法 - 中文版
repo_name: python数据结构和算法 - 中文版
repo_url: https://github.com/hellowac/pythonds-zh-cn/
site_description: 通过python解决算法和数据结构问题

# 主题配置
theme:
  name: material # 主题
  language: zh # 主题语言: 中文简体
  custom_dir: overrides # 自定义文件夹
  palette:
    primary: teal # 主题色
    accent: blue # 提示颜色
  features:
    - header.autohide # 顶部导航栏自动隐藏
    - navigation.top # 回到顶部按钮
    - navigation.tabs # 导航栏顶部tab化
    - navigation.tabs.sticky # 顶部导航栏始终显示
    - navigation.path # 路径导航支持
    - content.tabs.link # 支持tab内容标题的锚点
    - content.code.copy # 代码块支持拷贝
    - content.tooltips # 工具提示
    - navigation.indexes # 分组标题导航到index页面
    - navigation.prune # 导航修剪
    - navigation.instant # 即时加载

# 插件
plugins:
  - search # 搜索支持
  - mike # 支持文档版本化
  - autorefs # 锚点跨md文档支持
  - glightbox # 照片点击放大支持, 依赖Python包: mkdocs-glightbox
  # - mkdocstrings: # 支持从项目中生成文档, 依赖python包: mkdocstrings , https://github.com/mkdocstrings/mkdocstrings
  #           default_handler: python # 默认处理语言, 更多选项参考: https://mkdocstrings.github.io/usage/
  #           handlers:
  #                   python:
  #                           paths: [..] # 查找的模块，在上一级目录
  #                           options:
  #                                   show_bases: true # 显示继承的类
  #                                   show_root_heading: true # 显示顶级标题
  #                                   show_root_members_full_path: true # 显示顶级下面成员的全路径
  #                                   show_symbol_type_heading: true # 显示不同类标识符号
  #                                   members_order: "source" # 按成员在源文件中出现的顺序排序成员。
  #                                   merge_init_into_class: true # 是否将__init__方法合并到类的签名和文档字符串中
  #                                   show_if_no_docstring: false # 显示对象标题，即使它没有文档字符串或带有文档字符串的子项。
  #                                   show_signature: true # 显示方法和函数签名。
  #                                   show_signature_annotations: True # 在方法和函数签名中显示类型注释。
  #                                   separate_signature: True # 是否将整个签名放在标题下方的代码块中。
  #                                   docstring_section_style: table # 显示文档注释时的样式, list, https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_section_style
  #                                   docstring_style: google

  - git-revision-date-localized: # 支持文档创建时间显示， https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
      locale: zh
      enable_creation_date: true
      type: date

# 监听文件变动的目录 https://mkdocstrings.github.io/usage/#watch-directories
watch:
  - . # 包含父级源码目录

# 扩展
extra:
  version: # 支持文档版本化
    provider: mike # mike 部署支持

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

# 扩展支持， 支持数学符号
# extra_javascript:
#   - https://unpkg.com/mermaid@10.2.0/dist/mermaid.min.js
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/katex.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# markdown内部扩展配置
markdown_extensions:
  - abbr # 工具提示 支持
  - admonition # 忠告 支持
  - codehilite
  - def_list # 指定定义列表, 就是名称冒号内容的方式
  - attr_list # 支持标签里面的 属性定义
  - footnotes # 脚注支持
  - md_in_html
  - pymdownx.caret # 插入符支持
  - pymdownx.mark # 标记支持
  - pymdownx.tilde # 代字号支持
  - pymdownx.details # 详情可折叠，支持, 依赖 admonition
  - pymdownx.inlinehilite # 行内高亮显示
  - pymdownx.snippets
  - markdown.extensions.toc: # https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: true
  - pymdownx.highlight: # 高亮显示代码块  https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
      use_pygments: true
      pygments_lang_class: true
      noclasses: true
      pygments_style: default
  - pymdownx.superfences: # 一些扩展功能的基础定义
      custom_fences: # 代码块自定义
        - name: mermaid # mermaid图表支持
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist: # 任务列表支持
      custom_checkbox: true
  - pymdownx.tabbed: # 支持内容tab， 依赖 pymdownx.superfences
      alternate_style: true
  - pymdownx.critic: # 突出显示内容
      mode: view
  - pymdownx.keys # 键盘快捷键支持
  - pymdownx.smartsymbols # 智能符号
  - pymdownx.emoji: # emoji 表情支持  https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#emoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # 页面导航


  - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml
      generic: true

# 页面导航
nav:
  - 首页: index.md
  - 1. 引言:
      - c1/index.md
      - c1/s1.md
      - c1/s2.md
      - c1/s3.md
      - c1/s4.md
      - c1/s5.md
      - c1/s6.md
      - c1/s7.md
      - c1/s8.md
      - c1/s9.md
      - c1/s10.md
      - c1/s11.md
      - c1/s12.md
      - c1/s13.md
      - c1/s14.md
      - c1/s15.md
      - c1/s16.md
  - 2. 算法分析:
      - c2/index.md
      - c2/s1.md
      - c2/s2.md
      - c2/s3.md
      - c2/s4.md
      - c2/s5.md
      - c2/s6.md
      - c2/s7.md
      - c2/s8.md
      - c2/s9.md
      - c2/s10.md
  - 3. 基本数据结构:
      - c3/index.md
      - c3/s1.md
      - c3/s2.md
      - c3/s3.md
      - c3/s4.md
      - c3/s5.md
      - c3/s6.md
      - c3/s7.md
      - c3/s8.md
      - c3/s9.md
      - c3/s10.md
      - c3/s11.md
      - c3/s12.md
      - c3/s13.md
      - c3/s14.md
      - c3/s15.md
      - c3/s16.md
      - c3/s17.md
      - c3/s18.md
      - c3/s19.md
      - c3/s20.md
      - c3/s21.md
      - c3/s22.md
      - c3/s23.md
      - c3/s24.md
      - c3/s25.md
      - c3/s26.md
  - 4. 递归:
      - c4/index.md
      - c4/s1.md
      - c4/s2.md
      - c4/s3.md
      - c4/s4.md
      - c4/s5.md
      - c4/s6.md
      - c4/s7.md
      - c4/s8.md
      - c4/s9.md
      - c4/s10.md
      - c4/s11.md
      - c4/s12.md
      - c4/s13.md
      - c4/s14.md
      - c4/s15.md
  - 5. 搜索与排序:
      - c5/index.md
      - c5/s1.md
      - c5/s2.md
      - c5/s3.md
      - c5/s4.md
      - c5/s5.md
      - c5/s6.md
      - c5/s7.md
      - c5/s8.md
      - c5/s9.md
      - c5/s10.md
      - c5/s11.md
      - c5/s12.md
      - c5/s13.md
      - c5/s14.md
      - c5/s15.md
  - 6. 树和树算法:
      - c6/index.md
      - c6/s1.md
      - c6/s2.md
      - c6/s3.md
      - c6/s4.md
      - c6/s5.md
      - c6/s6.md
      - c6/s7.md
      - c6/s8.md
      - c6/s9.md
      - c6/s10.md
      - c6/s11.md
      - c6/s12.md
      - c6/s13.md
      - c6/s14.md
      - c6/s15.md
      - c6/s16.md
      - c6/s17.md
      - c6/s18.md
      - c6/s19.md
      - c6/s20.md
      - c6/s21.md
      - c6/s22.md
  - 7. 图和图算法:
      - c7/index.md
      - c7/s1.md
      - c7/s2.md
      - c7/s3.md
      - c7/s4.md
      - c7/s5.md
      - c7/s6.md
      - c7/s7.md
      - c7/s8.md
      - c7/s9.md
      - c7/s10.md
      - c7/s11.md
      - c7/s12.md
      - c7/s13.md
      - c7/s14.md
      - c7/s15.md
      - c7/s16.md
      - c7/s17.md
      - c7/s18.md
      - c7/s19.md
      - c7/s20.md
      - c7/s21.md
      - c7/s22.md
      - c7/s23.md
      - c7/s24.md
      - c7/s25.md
  - 8. 高级主题:
      - c8/index.md
      - c8/s1.md
      - c8/s2.md
      - c8/s3.md
      - c8/s4.md
      - c8/s5.md
      - c8/s6.md
